### ISSUE TITLE
Arranjar forma de remover a hero section de quando estamos numa pagina que nao a principal

### ISSUE THREAD

**Issue by JPUnD** [NFEF-FCUL/webpage#3]

**Comment by BGameiro2000** [comment]
Change hero section to include title o page and subtitle in e74009d37e213bb04f01ed881015d35b5d5f6b1a

**Comment by JPUnD** [comment]
nah nah era mesmo so aparecer o partial relevante e nao ter o hero

**Comment by BGameiro2000** [comment]
Devia de haver um título na página de qualquer forma. Para o editar é só modificar o `layouts/partials/hero.html`.

Vai-se dividir o hero do home (hero-home.html) e das outras páginas (hero.html).

**Comment by JPUnD** [comment]
para ficar mais pipi fazemos aquilo que foi sugerido na reuniao #8
