### ISSUE TITLE
arranjar forma de quando clicarmos num evento ir dar a pagina desse evento em vez de mostrar imagem maior

### ISSUE THREAD

**Issue by JPUnD** [NFEF-FCUL/webpage#5]

**Comment by BGameiro2000** [comment]
Events need a page before this could be added.

**Comment by JPUnD** [comment]
ja existe pagina dos eventos

**Comment by JPUnD** [comment]
vou fechar isto pq tenho tudo num issue do github onde se inclui melhorar a pagina eventos
